/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeskRouteRouteImport } from './routes/desk/route'
import { Route as ForgeRouteImport } from './routes/forge'
import { Route as GamesRouteImport } from './routes/games'
import { Route as InRouteImport } from './routes/in'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketRouteImport } from './routes/market'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReachRouteImport } from './routes/reach'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as ShieldRouteImport } from './routes/shield'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SoftwareRouteImport } from './routes/software'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThroneRouteRouteImport } from './routes/throne/route'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as WatchRouteRouteImport } from './routes/watch/route'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as CheckoutCancelRouteImport } from './routes/checkout.cancel'
import { Route as CheckoutCompleteRouteImport } from './routes/checkout.complete'
import { Route as DeskIndexRouteImport } from './routes/desk/index'
import { Route as DeskCampaignsRouteImport } from './routes/desk/campaigns'
import { Route as DeskComplianceRouteImport } from './routes/desk/compliance'
import { Route as DeskProductsRouteImport } from './routes/desk/products'
import { Route as DeskTicketsRouteImport } from './routes/desk/tickets'
import { Route as DeskUsersRouteImport } from './routes/desk/users'
import { Route as MarketSlugRouteImport } from './routes/market.$slug'
import { Route as ThroneIndexRouteImport } from './routes/throne/index'
import { Route as ThroneAnalyticsRouteImport } from './routes/throne/analytics'
import { Route as ThroneArchitectRouteImport } from './routes/throne/architect'
import { Route as ThroneAuditRouteImport } from './routes/throne/audit'
import { Route as ThroneGodCodesRouteImport } from './routes/throne/god-codes'
import { Route as ThronePaymentsRouteImport } from './routes/throne/payments'
import { Route as ThroneProductsRouteImport } from './routes/throne/products'
import { Route as ThroneRecoveryRouteImport } from './routes/throne/recovery'
import { Route as ThroneSecurityRouteImport } from './routes/throne/security'
import { Route as ThroneSentinelRouteImport } from './routes/throne/sentinel'
import { Route as ThroneShieldRouteImport } from './routes/throne/shield'
import { Route as ThroneStaffRouteImport } from './routes/throne/staff'
import { Route as ThroneUsersRouteImport } from './routes/throne/users'
import { Route as WatchIndexRouteImport } from './routes/watch/index'
import { Route as WatchAuditRouteImport } from './routes/watch/audit'
import { Route as WatchIncidentsRouteImport } from './routes/watch/incidents'
import { Route as WatchReportsRouteImport } from './routes/watch/reports'
import { Route as WatchScannerRouteImport } from './routes/watch/scanner'
import { Route as WatchStaffRouteImport } from './routes/watch/staff'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRouteRoute = DeskRouteRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const InRoute = InRouteImport.update({
  id: '/in',
  path: '/in',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReachRoute = ReachRouteImport.update({
  id: '/reach',
  path: '/reach',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ShieldRoute = ShieldRouteImport.update({
  id: '/shield',
  path: '/shield',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThroneRouteRoute = ThroneRouteRouteImport.update({
  id: '/throne',
  path: '/throne',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRouteRoute = WatchRouteRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCompleteRoute = CheckoutCompleteRouteImport.update({
  id: '/checkout/complete',
  path: '/checkout/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskCampaignsRoute = DeskCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskComplianceRoute = DeskComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskProductsRoute = DeskProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskTicketsRoute = DeskTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskUsersRoute = DeskUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DeskRouteRoute,
} as any)
const MarketSlugRoute = MarketSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarketRoute,
} as any)
const ThroneIndexRoute = ThroneIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThroneRouteRoute,
} as any)
const ThroneAnalyticsRoute = ThroneAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ThroneRouteRoute,
} as any)
const ThroneArchitectRoute = ThroneArchitectRouteImport.update({
  id: '/architect',
  path: '/architect',
  getParentRoute: () => ThroneRouteRoute,
} as any)
const ThroneAuditRoute = ThroneAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ThroneRouteRoute,
} as any)
const ThroneGodCodesRoute = ThroneGodCodesRouteImport.update({
  id: '/god-codes',
  path: '/god-codes',
  getParentRoute: () => ThroneRouteRoute,
} as any)
const ThronePaymentsRoute = ThronePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ThroneRouteRoute,
} as any)
const ThroneProductsRoute = ThroneProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ThroneRouteRoute,
} as any)
const ThroneRecoveryRoute = ThroneRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => ThroneRouteRoute,
} as any)
const ThroneSecurityRoute = ThroneSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => ThroneRouteRoute,
} as any)
const ThroneSentinelRoute = ThroneSentinelRouteImport.update({
  id: '/sentinel',
  path: '/sentinel',
  getParentRoute: () => ThroneRouteRoute,
} as any)
const ThroneShieldRoute = ThroneShieldRouteImport.update({
  id: '/shield',
  path: '/shield',
  getParentRoute: () => ThroneRouteRoute,
} as any)
const ThroneStaffRoute = ThroneStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ThroneRouteRoute,
} as any)
const ThroneUsersRoute = ThroneUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ThroneRouteRoute,
} as any)
const WatchIndexRoute = WatchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WatchRouteRoute,
} as any)
const WatchAuditRoute = WatchAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => WatchRouteRoute,
} as any)
const WatchIncidentsRoute = WatchIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => WatchRouteRoute,
} as any)
const WatchReportsRoute = WatchReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => WatchRouteRoute,
} as any)
const WatchScannerRoute = WatchScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => WatchRouteRoute,
} as any)
const WatchStaffRoute = WatchStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => WatchRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRouteRouteWithChildren
  '/throne': typeof ThroneRouteRouteWithChildren
  '/watch': typeof WatchRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/apps': typeof AppsRoute
  '/contact': typeof ContactRoute
  '/forge': typeof ForgeRoute
  '/games': typeof GamesRoute
  '/in': typeof InRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reach': typeof ReachRoute
  '/redeem': typeof RedeemRoute
  '/shield': typeof ShieldRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/software': typeof SoftwareRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/complete': typeof CheckoutCompleteRoute
  '/desk/campaigns': typeof DeskCampaignsRoute
  '/desk/compliance': typeof DeskComplianceRoute
  '/desk/products': typeof DeskProductsRoute
  '/desk/tickets': typeof DeskTicketsRoute
  '/desk/users': typeof DeskUsersRoute
  '/market/$slug': typeof MarketSlugRoute
  '/throne/analytics': typeof ThroneAnalyticsRoute
  '/throne/architect': typeof ThroneArchitectRoute
  '/throne/audit': typeof ThroneAuditRoute
  '/throne/god-codes': typeof ThroneGodCodesRoute
  '/throne/payments': typeof ThronePaymentsRoute
  '/throne/products': typeof ThroneProductsRoute
  '/throne/recovery': typeof ThroneRecoveryRoute
  '/throne/security': typeof ThroneSecurityRoute
  '/throne/sentinel': typeof ThroneSentinelRoute
  '/throne/shield': typeof ThroneShieldRoute
  '/throne/staff': typeof ThroneStaffRoute
  '/throne/users': typeof ThroneUsersRoute
  '/watch/audit': typeof WatchAuditRoute
  '/watch/incidents': typeof WatchIncidentsRoute
  '/watch/reports': typeof WatchReportsRoute
  '/watch/scanner': typeof WatchScannerRoute
  '/watch/staff': typeof WatchStaffRoute
  '/desk/': typeof DeskIndexRoute
  '/throne/': typeof ThroneIndexRoute
  '/watch/': typeof WatchIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/apps': typeof AppsRoute
  '/contact': typeof ContactRoute
  '/forge': typeof ForgeRoute
  '/games': typeof GamesRoute
  '/in': typeof InRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reach': typeof ReachRoute
  '/redeem': typeof RedeemRoute
  '/shield': typeof ShieldRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/software': typeof SoftwareRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/complete': typeof CheckoutCompleteRoute
  '/desk/campaigns': typeof DeskCampaignsRoute
  '/desk/compliance': typeof DeskComplianceRoute
  '/desk/products': typeof DeskProductsRoute
  '/desk/tickets': typeof DeskTicketsRoute
  '/desk/users': typeof DeskUsersRoute
  '/market/$slug': typeof MarketSlugRoute
  '/throne/analytics': typeof ThroneAnalyticsRoute
  '/throne/architect': typeof ThroneArchitectRoute
  '/throne/audit': typeof ThroneAuditRoute
  '/throne/god-codes': typeof ThroneGodCodesRoute
  '/throne/payments': typeof ThronePaymentsRoute
  '/throne/products': typeof ThroneProductsRoute
  '/throne/recovery': typeof ThroneRecoveryRoute
  '/throne/security': typeof ThroneSecurityRoute
  '/throne/sentinel': typeof ThroneSentinelRoute
  '/throne/shield': typeof ThroneShieldRoute
  '/throne/staff': typeof ThroneStaffRoute
  '/throne/users': typeof ThroneUsersRoute
  '/watch/audit': typeof WatchAuditRoute
  '/watch/incidents': typeof WatchIncidentsRoute
  '/watch/reports': typeof WatchReportsRoute
  '/watch/scanner': typeof WatchScannerRoute
  '/watch/staff': typeof WatchStaffRoute
  '/desk': typeof DeskIndexRoute
  '/throne': typeof ThroneIndexRoute
  '/watch': typeof WatchIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desk': typeof DeskRouteRouteWithChildren
  '/throne': typeof ThroneRouteRouteWithChildren
  '/watch': typeof WatchRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/apps': typeof AppsRoute
  '/contact': typeof ContactRoute
  '/forge': typeof ForgeRoute
  '/games': typeof GamesRoute
  '/in': typeof InRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reach': typeof ReachRoute
  '/redeem': typeof RedeemRoute
  '/shield': typeof ShieldRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/software': typeof SoftwareRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/complete': typeof CheckoutCompleteRoute
  '/desk/campaigns': typeof DeskCampaignsRoute
  '/desk/compliance': typeof DeskComplianceRoute
  '/desk/products': typeof DeskProductsRoute
  '/desk/tickets': typeof DeskTicketsRoute
  '/desk/users': typeof DeskUsersRoute
  '/market/$slug': typeof MarketSlugRoute
  '/throne/analytics': typeof ThroneAnalyticsRoute
  '/throne/architect': typeof ThroneArchitectRoute
  '/throne/audit': typeof ThroneAuditRoute
  '/throne/god-codes': typeof ThroneGodCodesRoute
  '/throne/payments': typeof ThronePaymentsRoute
  '/throne/products': typeof ThroneProductsRoute
  '/throne/recovery': typeof ThroneRecoveryRoute
  '/throne/security': typeof ThroneSecurityRoute
  '/throne/sentinel': typeof ThroneSentinelRoute
  '/throne/shield': typeof ThroneShieldRoute
  '/throne/staff': typeof ThroneStaffRoute
  '/throne/users': typeof ThroneUsersRoute
  '/watch/audit': typeof WatchAuditRoute
  '/watch/incidents': typeof WatchIncidentsRoute
  '/watch/reports': typeof WatchReportsRoute
  '/watch/scanner': typeof WatchScannerRoute
  '/watch/staff': typeof WatchStaffRoute
  '/desk/': typeof DeskIndexRoute
  '/throne/': typeof ThroneIndexRoute
  '/watch/': typeof WatchIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desk'
    | '/throne'
    | '/watch'
    | '/about'
    | '/account'
    | '/admin'
    | '/agents'
    | '/apps'
    | '/contact'
    | '/forge'
    | '/games'
    | '/in'
    | '/login'
    | '/market'
    | '/pricing'
    | '/privacy'
    | '/reach'
    | '/redeem'
    | '/shield'
    | '/signup'
    | '/sitemap.xml'
    | '/software'
    | '/team'
    | '/terms'
    | '/tools'
    | '/checkout/$slug'
    | '/checkout/cancel'
    | '/checkout/complete'
    | '/desk/campaigns'
    | '/desk/compliance'
    | '/desk/products'
    | '/desk/tickets'
    | '/desk/users'
    | '/market/$slug'
    | '/throne/analytics'
    | '/throne/architect'
    | '/throne/audit'
    | '/throne/god-codes'
    | '/throne/payments'
    | '/throne/products'
    | '/throne/recovery'
    | '/throne/security'
    | '/throne/sentinel'
    | '/throne/shield'
    | '/throne/staff'
    | '/throne/users'
    | '/watch/audit'
    | '/watch/incidents'
    | '/watch/reports'
    | '/watch/scanner'
    | '/watch/staff'
    | '/desk/'
    | '/throne/'
    | '/watch/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/agents'
    | '/apps'
    | '/contact'
    | '/forge'
    | '/games'
    | '/in'
    | '/login'
    | '/market'
    | '/pricing'
    | '/privacy'
    | '/reach'
    | '/redeem'
    | '/shield'
    | '/signup'
    | '/sitemap.xml'
    | '/software'
    | '/team'
    | '/terms'
    | '/tools'
    | '/checkout/$slug'
    | '/checkout/cancel'
    | '/checkout/complete'
    | '/desk/campaigns'
    | '/desk/compliance'
    | '/desk/products'
    | '/desk/tickets'
    | '/desk/users'
    | '/market/$slug'
    | '/throne/analytics'
    | '/throne/architect'
    | '/throne/audit'
    | '/throne/god-codes'
    | '/throne/payments'
    | '/throne/products'
    | '/throne/recovery'
    | '/throne/security'
    | '/throne/sentinel'
    | '/throne/shield'
    | '/throne/staff'
    | '/throne/users'
    | '/watch/audit'
    | '/watch/incidents'
    | '/watch/reports'
    | '/watch/scanner'
    | '/watch/staff'
    | '/desk'
    | '/throne'
    | '/watch'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/desk'
    | '/throne'
    | '/watch'
    | '/about'
    | '/account'
    | '/admin'
    | '/agents'
    | '/apps'
    | '/contact'
    | '/forge'
    | '/games'
    | '/in'
    | '/login'
    | '/market'
    | '/pricing'
    | '/privacy'
    | '/reach'
    | '/redeem'
    | '/shield'
    | '/signup'
    | '/sitemap.xml'
    | '/software'
    | '/team'
    | '/terms'
    | '/tools'
    | '/checkout/$slug'
    | '/checkout/cancel'
    | '/checkout/complete'
    | '/desk/campaigns'
    | '/desk/compliance'
    | '/desk/products'
    | '/desk/tickets'
    | '/desk/users'
    | '/market/$slug'
    | '/throne/analytics'
    | '/throne/architect'
    | '/throne/audit'
    | '/throne/god-codes'
    | '/throne/payments'
    | '/throne/products'
    | '/throne/recovery'
    | '/throne/security'
    | '/throne/sentinel'
    | '/throne/shield'
    | '/throne/staff'
    | '/throne/users'
    | '/watch/audit'
    | '/watch/incidents'
    | '/watch/reports'
    | '/watch/scanner'
    | '/watch/staff'
    | '/desk/'
    | '/throne/'
    | '/watch/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeskRouteRoute: typeof DeskRouteRouteWithChildren
  ThroneRouteRoute: typeof ThroneRouteRouteWithChildren
  WatchRouteRoute: typeof WatchRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AgentsRoute: typeof AgentsRoute
  AppsRoute: typeof AppsRoute
  ContactRoute: typeof ContactRoute
  ForgeRoute: typeof ForgeRoute
  GamesRoute: typeof GamesRoute
  InRoute: typeof InRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReachRoute: typeof ReachRoute
  RedeemRoute: typeof RedeemRoute
  ShieldRoute: typeof ShieldRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoftwareRoute: typeof SoftwareRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutCompleteRoute: typeof CheckoutCompleteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/in': {
      id: '/in'
      path: '/in'
      fullPath: '/in'
      preLoaderRoute: typeof InRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reach': {
      id: '/reach'
      path: '/reach'
      fullPath: '/reach'
      preLoaderRoute: typeof ReachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shield': {
      id: '/shield'
      path: '/shield'
      fullPath: '/shield'
      preLoaderRoute: typeof ShieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/throne': {
      id: '/throne'
      path: '/throne'
      fullPath: '/throne'
      preLoaderRoute: typeof ThroneRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/complete': {
      id: '/checkout/complete'
      path: '/checkout/complete'
      fullPath: '/checkout/complete'
      preLoaderRoute: typeof CheckoutCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/campaigns': {
      id: '/desk/campaigns'
      path: '/campaigns'
      fullPath: '/desk/campaigns'
      preLoaderRoute: typeof DeskCampaignsRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/compliance': {
      id: '/desk/compliance'
      path: '/compliance'
      fullPath: '/desk/compliance'
      preLoaderRoute: typeof DeskComplianceRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/products': {
      id: '/desk/products'
      path: '/products'
      fullPath: '/desk/products'
      preLoaderRoute: typeof DeskProductsRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/tickets': {
      id: '/desk/tickets'
      path: '/tickets'
      fullPath: '/desk/tickets'
      preLoaderRoute: typeof DeskTicketsRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/users': {
      id: '/desk/users'
      path: '/users'
      fullPath: '/desk/users'
      preLoaderRoute: typeof DeskUsersRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/market/$slug': {
      id: '/market/$slug'
      path: '/$slug'
      fullPath: '/market/$slug'
      preLoaderRoute: typeof MarketSlugRouteImport
      parentRoute: typeof MarketRoute
    }
    '/throne/': {
      id: '/throne/'
      path: '/'
      fullPath: '/throne/'
      preLoaderRoute: typeof ThroneIndexRouteImport
      parentRoute: typeof ThroneRouteRoute
    }
    '/throne/analytics': {
      id: '/throne/analytics'
      path: '/analytics'
      fullPath: '/throne/analytics'
      preLoaderRoute: typeof ThroneAnalyticsRouteImport
      parentRoute: typeof ThroneRouteRoute
    }
    '/throne/architect': {
      id: '/throne/architect'
      path: '/architect'
      fullPath: '/throne/architect'
      preLoaderRoute: typeof ThroneArchitectRouteImport
      parentRoute: typeof ThroneRouteRoute
    }
    '/throne/audit': {
      id: '/throne/audit'
      path: '/audit'
      fullPath: '/throne/audit'
      preLoaderRoute: typeof ThroneAuditRouteImport
      parentRoute: typeof ThroneRouteRoute
    }
    '/throne/god-codes': {
      id: '/throne/god-codes'
      path: '/god-codes'
      fullPath: '/throne/god-codes'
      preLoaderRoute: typeof ThroneGodCodesRouteImport
      parentRoute: typeof ThroneRouteRoute
    }
    '/throne/payments': {
      id: '/throne/payments'
      path: '/payments'
      fullPath: '/throne/payments'
      preLoaderRoute: typeof ThronePaymentsRouteImport
      parentRoute: typeof ThroneRouteRoute
    }
    '/throne/products': {
      id: '/throne/products'
      path: '/products'
      fullPath: '/throne/products'
      preLoaderRoute: typeof ThroneProductsRouteImport
      parentRoute: typeof ThroneRouteRoute
    }
    '/throne/recovery': {
      id: '/throne/recovery'
      path: '/recovery'
      fullPath: '/throne/recovery'
      preLoaderRoute: typeof ThroneRecoveryRouteImport
      parentRoute: typeof ThroneRouteRoute
    }
    '/throne/security': {
      id: '/throne/security'
      path: '/security'
      fullPath: '/throne/security'
      preLoaderRoute: typeof ThroneSecurityRouteImport
      parentRoute: typeof ThroneRouteRoute
    }
    '/throne/sentinel': {
      id: '/throne/sentinel'
      path: '/sentinel'
      fullPath: '/throne/sentinel'
      preLoaderRoute: typeof ThroneSentinelRouteImport
      parentRoute: typeof ThroneRouteRoute
    }
    '/throne/shield': {
      id: '/throne/shield'
      path: '/shield'
      fullPath: '/throne/shield'
      preLoaderRoute: typeof ThroneShieldRouteImport
      parentRoute: typeof ThroneRouteRoute
    }
    '/throne/staff': {
      id: '/throne/staff'
      path: '/staff'
      fullPath: '/throne/staff'
      preLoaderRoute: typeof ThroneStaffRouteImport
      parentRoute: typeof ThroneRouteRoute
    }
    '/throne/users': {
      id: '/throne/users'
      path: '/users'
      fullPath: '/throne/users'
      preLoaderRoute: typeof ThroneUsersRouteImport
      parentRoute: typeof ThroneRouteRoute
    }
    '/watch/': {
      id: '/watch/'
      path: '/'
      fullPath: '/watch/'
      preLoaderRoute: typeof WatchIndexRouteImport
      parentRoute: typeof WatchRouteRoute
    }
    '/watch/audit': {
      id: '/watch/audit'
      path: '/audit'
      fullPath: '/watch/audit'
      preLoaderRoute: typeof WatchAuditRouteImport
      parentRoute: typeof WatchRouteRoute
    }
    '/watch/incidents': {
      id: '/watch/incidents'
      path: '/incidents'
      fullPath: '/watch/incidents'
      preLoaderRoute: typeof WatchIncidentsRouteImport
      parentRoute: typeof WatchRouteRoute
    }
    '/watch/reports': {
      id: '/watch/reports'
      path: '/reports'
      fullPath: '/watch/reports'
      preLoaderRoute: typeof WatchReportsRouteImport
      parentRoute: typeof WatchRouteRoute
    }
    '/watch/scanner': {
      id: '/watch/scanner'
      path: '/scanner'
      fullPath: '/watch/scanner'
      preLoaderRoute: typeof WatchScannerRouteImport
      parentRoute: typeof WatchRouteRoute
    }
    '/watch/staff': {
      id: '/watch/staff'
      path: '/staff'
      fullPath: '/watch/staff'
      preLoaderRoute: typeof WatchStaffRouteImport
      parentRoute: typeof WatchRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DeskRouteRouteChildren {
  DeskCampaignsRoute: typeof DeskCampaignsRoute
  DeskComplianceRoute: typeof DeskComplianceRoute
  DeskProductsRoute: typeof DeskProductsRoute
  DeskTicketsRoute: typeof DeskTicketsRoute
  DeskUsersRoute: typeof DeskUsersRoute
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteRouteChildren: DeskRouteRouteChildren = {
  DeskCampaignsRoute: DeskCampaignsRoute,
  DeskComplianceRoute: DeskComplianceRoute,
  DeskProductsRoute: DeskProductsRoute,
  DeskTicketsRoute: DeskTicketsRoute,
  DeskUsersRoute: DeskUsersRoute,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteRouteWithChildren = DeskRouteRoute._addFileChildren(
  DeskRouteRouteChildren,
)

interface ThroneRouteRouteChildren {
  ThroneAnalyticsRoute: typeof ThroneAnalyticsRoute
  ThroneArchitectRoute: typeof ThroneArchitectRoute
  ThroneAuditRoute: typeof ThroneAuditRoute
  ThroneGodCodesRoute: typeof ThroneGodCodesRoute
  ThronePaymentsRoute: typeof ThronePaymentsRoute
  ThroneProductsRoute: typeof ThroneProductsRoute
  ThroneRecoveryRoute: typeof ThroneRecoveryRoute
  ThroneSecurityRoute: typeof ThroneSecurityRoute
  ThroneSentinelRoute: typeof ThroneSentinelRoute
  ThroneShieldRoute: typeof ThroneShieldRoute
  ThroneStaffRoute: typeof ThroneStaffRoute
  ThroneUsersRoute: typeof ThroneUsersRoute
  ThroneIndexRoute: typeof ThroneIndexRoute
}

const ThroneRouteRouteChildren: ThroneRouteRouteChildren = {
  ThroneAnalyticsRoute: ThroneAnalyticsRoute,
  ThroneArchitectRoute: ThroneArchitectRoute,
  ThroneAuditRoute: ThroneAuditRoute,
  ThroneGodCodesRoute: ThroneGodCodesRoute,
  ThronePaymentsRoute: ThronePaymentsRoute,
  ThroneProductsRoute: ThroneProductsRoute,
  ThroneRecoveryRoute: ThroneRecoveryRoute,
  ThroneSecurityRoute: ThroneSecurityRoute,
  ThroneSentinelRoute: ThroneSentinelRoute,
  ThroneShieldRoute: ThroneShieldRoute,
  ThroneStaffRoute: ThroneStaffRoute,
  ThroneUsersRoute: ThroneUsersRoute,
  ThroneIndexRoute: ThroneIndexRoute,
}

const ThroneRouteRouteWithChildren = ThroneRouteRoute._addFileChildren(
  ThroneRouteRouteChildren,
)

interface WatchRouteRouteChildren {
  WatchAuditRoute: typeof WatchAuditRoute
  WatchIncidentsRoute: typeof WatchIncidentsRoute
  WatchReportsRoute: typeof WatchReportsRoute
  WatchScannerRoute: typeof WatchScannerRoute
  WatchStaffRoute: typeof WatchStaffRoute
  WatchIndexRoute: typeof WatchIndexRoute
}

const WatchRouteRouteChildren: WatchRouteRouteChildren = {
  WatchAuditRoute: WatchAuditRoute,
  WatchIncidentsRoute: WatchIncidentsRoute,
  WatchReportsRoute: WatchReportsRoute,
  WatchScannerRoute: WatchScannerRoute,
  WatchStaffRoute: WatchStaffRoute,
  WatchIndexRoute: WatchIndexRoute,
}

const WatchRouteRouteWithChildren = WatchRouteRoute._addFileChildren(
  WatchRouteRouteChildren,
)

interface MarketRouteChildren {
  MarketSlugRoute: typeof MarketSlugRoute
}

const MarketRouteChildren: MarketRouteChildren = {
  MarketSlugRoute: MarketSlugRoute,
}

const MarketRouteWithChildren =
  MarketRoute._addFileChildren(MarketRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeskRouteRoute: DeskRouteRouteWithChildren,
  ThroneRouteRoute: ThroneRouteRouteWithChildren,
  WatchRouteRoute: WatchRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AgentsRoute: AgentsRoute,
  AppsRoute: AppsRoute,
  ContactRoute: ContactRoute,
  ForgeRoute: ForgeRoute,
  GamesRoute: GamesRoute,
  InRoute: InRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReachRoute: ReachRoute,
  RedeemRoute: RedeemRoute,
  ShieldRoute: ShieldRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoftwareRoute: SoftwareRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutCompleteRoute: CheckoutCompleteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
